### ISSUE TITLE
Push to sub-directory?

### ISSUE THREAD

**Issue by jblanton** [laurilehmijoki/jekyll-s3#20]
I'm going to be using Jekyll to host two blogs on the same domain--one at "/" and one at "/subdir". Is there a way to tell Jekyll-s3 to push to the subdir? (I realize that I may be able to get around this by telling Jekyll to write the files for the second blog into /subdir, but I haven't really looked into that yet.)

**Comment by laurilehmijoki** [comment]
At the moment, no.

Out of curiosity, why would you want to host two different Jekyll blogs on the same S3 bucket?

**Comment by jblanton** [comment]
Ah, OK, thanks for getting back to me.

To answer your question, I'll be running a blog at domain.com and a photoblog at domain.com/photos, each styled, etc., differently.

**Comment by adelevie** [comment]
You'd want something like this?

``` yml
s3_id: YOUR_AWS_S3_ACCESS_KEY_ID
s3_secret: YOUR_AWS_S3_SECRET_ACCESS_KEY
s3_bucket: your.blog.bucket.com
s3_bucket_directory: /photos
```

There could be something under the hood where "s3_bucket_subdirectory" simply defaults to "/" if `nil?`.
