### ISSUE TITLE
read ID & Secret from environment variables?

### ISSUE THREAD

**Issue by troygoode** [laurilehmijoki/jekyll-s3#44]
I'd like to commit my `_jekyll_s3.yml` file to my git repo, but don't want to do so with my AWS id & secret included. It'd be nice if the `config_loader` would look at environment variables if `s3_id` and/or `s3_secret` weren't specified in the config file.

**Comment by adelevie** [comment]
Isn't this possible by using ERB in the yaml file?

**Comment by troygoode** [comment]
so it is! thanks @adelevie 

In case anyone else runs into this (that, like me, hasn't done a lot of Ruby before) - my `_jekyll_s3.yml` file looks like this now:

``` yaml
s3_id: <%= ENV['S3_ID'] %>
s3_secret: <%= ENV['S3_SECRET'] %>
se_bucket: blog.example.com %>
```
